project:
  type: website
  output-dir: docs

website:
  title: "Nishil Jaiswal"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: cv.pdf
        text: CV
      - text: Assignments
        menu:
          - href: as1.qmd
            text: Assignment 1
          - href: as1.qmd
            text: Assignment 2
          - href: as3.qmd
            text: Assignment 3
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

