project:
  type: website
  output-dir: docs

website:
  title: "Nishil Jaiswal"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cv.pdf
        text: CV

      - href: labs.qmd
        text: Labs
      - href: assignments.qmd
        text: Assignments
      - href: project.qmd
        text: Project      
      - href: about.qmd
        text: About

        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

